version: '3'
services:
  router:
    restart: always
    build: "./docker/router"
    ports:
      - "443:443"
  https-portal:
    image: hello-world
  web:
    restart: always
    build: "./docker/web"
    volumes:
      - ./website:/var/www/html
    environment:
      - TZ=Asia/Tokyo
  legacyweb:
    restart: always
    build: "./docker/legacyweb"
    environment:
      - TZ=Asia/Tokyo
  dns:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    entrypoint:
      - /zdxsv
      - -v=1
      - dns
      - /config.toml
    ports:
      - "53:53/udp"
    environment:
      - TZ=Asia/Tokyo
  login:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    volumes:
      - ./zdxsv.db:/zdxsv.db
    entrypoint:
      - /zdxsv
      - -v=1
      - login
      - /config.toml
    environment:
      - TZ=Asia/Tokyo
  lobby:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    ports:
      - "8200:8200"
      - "8201:8201"     # for UDP proxy
      - "8201:8201/udp" # for UDP proxy
    volumes:
      - ./zdxsv.db:/zdxsv.db
    entrypoint:
      - /zdxsv
      - -v=1
      - lobby
      - /config.toml
    environment:
      - TZ=Asia/Tokyo
  battle:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    ports:
      - "8210:8210"
      - "8210:8210/udp"
    entrypoint:
      - /zdxsv
      - -v=1
      - battle
      - /config.toml
    environment:
      - TZ=Asia/Tokyo
  status:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    entrypoint:
      - /zdxsv
      - -v=1
      - status
      - /config.toml
    environment:
      - TZ=Asia/Tokyo
