version: '3'
services:
  https-portal:
    build: "./docker/https-portal"
    restart: always
    environment:
      DOMAINS: 'zdxsv.example.com -> http://web:80'
      STAGE: 'local'
  web:
    ports:
      - "80:80"
  dns:
    volumes:
      - ./dev.toml:/config.toml
  login:
    volumes:
      - ./dev.toml:/config.toml
  lobby:
    network_mode: "host"
    volumes:
      - ./dev.toml:/config.toml
  battle:
    network_mode: "host"
    volumes:
      - ./dev.toml:/config.toml
  status:
    environment:
      - ZDXSV_ON_DOCKER_HOST=lobby,battle
    volumes:
      - ./dev.toml:/config.toml
