version: '3.7'
services:
  https-portal:
    build: "./docker/https-portal"
    restart: always
    environment:
      DOMAINS: 'zdxsv.example.com -> http://web:80'
      STAGE: 'local'
  web:
    ports:
      - "80:80"
  lobby:
    network_mode: "host"
    environment:
      - ZDXSV_BATTLE_RPC_ADDR=":3080"
      - ZDXSV_LOBBY_RPC_ADDR=":8201"
  battle:
    network_mode: "host"
      - ZDXSV_BATTLE_RPC_ADDR=":3080"
      - ZDXSV_LOBBY_RPC_ADDR=":8201"
  status:
    environment:
      - ZDXSV_BATTLE_RPC_ADDR=":3080"
      - ZDXSV_LOBBY_RPC_ADDR=":8201"
