version: '3'
services:
  dns:
    volumes:
      - ./dev.toml:/config.toml
  login:
    volumes:
      - ./dev.toml:/config.toml
  lobby:
    network_mode: "host"
    volumes:
      - ./dev.toml:/config.toml
  battle:
    network_mode: "host"
    volumes:
      - ./dev.toml:/config.toml
  status:
    environment:
      - ZDXSV_ON_DOCKER_HOST=lobby,battle
    volumes:
      - ./dev.toml:/config.toml
