version: '3.7'
services:
  https-portal:
    build: "./docker/https-portal"
    restart: always
    environment:
      DOMAINS: 'zdxsv.example.com -> http://web:80'
      STAGE: 'local'
  web:
    ports:
      - "80:80"
  lobby:
    network_mode: "host"
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    command: lobby
  battle:
    network_mode: "host"
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    command: battle
