version: '3'
services:
  router:
    restart: always
    build: "./docker/router"
    ports:
      - "443:443"
  web:
    restart: always
    build: "./docker/web"
    volumes:
      - ./website:/var/www/html
  legacyweb:
    restart: always
    build: "./docker/legacyweb"
  dns:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    entrypoint:
      - /zdxsv
      - -v=1
      - dns
      - /config.toml
    ports:
      - "53:53/udp"
  login:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    volumes:
      - ./zdxsv.db:/zdxsv.db
    entrypoint:
      - /zdxsv
      - -v=1
      - login
      - /config.toml
  lobby:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    ports:
      - "8200:8200"
      - "8201:8201"     # for UDP proxy
      - "8201:8201/udp" # for UDP proxy
    volumes:
      - ./zdxsv.db:/zdxsv.db
    entrypoint:
      - /zdxsv
      - -v=1
      - lobby
      - /config.toml
  battle:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    ports:
      - "8210:8210"
      - "8210:8210/udp"
    entrypoint:
      - /zdxsv
      - -v=1
      - battle
      - /config.toml
  status:
    build:
      context: .
      dockerfile: "./docker/zdxsv/Dockerfile"
    entrypoint:
      - /zdxsv
      - -v=1
      - status
      - /config.toml
