[dnas]
public_addr = "192.168.0.13"

[login]
addr = ":80"
public_addr = "192.168.0.13"

[lobby]
addr = ":8200"
rpc_addr = "lobby:8201"
public_addr = "192.168.0.13:8200"
backdoor = ":8200"

[battle]
addr = ":8210"
rpc_addr = "battle:3080"
public_addr = "192.168.0.13:8210"

[status]
addr = ":8080"

[db]
name = "zdxsv.db"
